apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: miufwpl34-go 
  janus-idp.io/tekton: miufwpl34-go
  backstage.io/kubernetes-id: miufwpl34-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: miufwpl34-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml